swipe: 
  4:
    left: 
      command: 'xdotool key alt+Left'
    right: 
      command: 'xdotool key alt+Right'
    up: 
      command: 'xdotool key super'
    down: 
      command: 'xdotool key super+d'
  3:
    left: 
      command: 'xdotool key super+Left'
    right: 
      command: 'xdotool key super+Right' 
    up: 
      command: 'xdotool key super+Up'
    down: 
      command: 'xdotool key super+Down'
pinch:
  3:
    in:
      command: 'xdotool key ctrl+plus'
    out:
      command: 'xdotool key ctrl+minus'
  4:
    in:
      command: 'xdotool key super+a'
    out:
      command: 'xdotool key super+s'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
